### ISSUE TITLE
Installing on Azure DevOps does not allow selection as a task

### ISSUE THREAD

**Issue by sedarby2018** [jeffpriz/vsts-json-to-variable#10]

**Comment by jeffpriz** [comment]
can you please explain? I utilize this on Azure DevOps today with no issues.. here is a screenshot of selecting the task
![image](https://user-images.githubusercontent.com/10476939/48737656-3fe0d380-ec14-11e8-9c4d-d21ffcac4512.png)

**Comment by jeffpriz** [comment]
I just uninstalled and re-installed the extension from the marketplace to ensure I wasn't doing anything "odd".. but no change.  I would love more feedback/details... I had somebody uninstall and leave a comment that they could not find the task.. curious about what the troubles are.

thanks

jeff

**Comment by kesavramesh** [comment]
Here is a screen shot of what we are seeing in our task

**Comment by jeffpriz** [comment]
@kesavramesh thanks.. hmm, that is odd. Is this just a session/cache issue? If you close the browser after installing does this get found?  Here is a screenshot of me adding the task to a release pipeline through search:
![image](https://user-images.githubusercontent.com/10476939/48739342-4f165000-ec19-11e8-90c7-9abc26d21d99.png)

**Comment by jeffpriz** [comment]
@kesavramesh  or do you find it in the task list under the Utility tasks?

**Comment by kesavramesh** [comment]
NO

**Comment by kesavramesh** [comment]
Rest Call which also says "Installed" but allows me to be ADDED
But Json toVariable I am seeing only as "Installed" and does not give me option to "ADD"

![restcall](https://user-images.githubusercontent.com/45183803/48740368-32801500-ec25-11e8-963b-7e7d238f9e34.jpg)

**Comment by kesavramesh** [comment]
Jeff, 
It took some time for the extension to show up with ADD button. It seems ADO took time to process this extension.

Now I have the next question,
I have the sonarqube analysis output file which is a JSON file which I gave as an input to your extension and parsed the same.
Here is the sample image output 

Variable Name Prefix=hotel_json
Creating variable : hotel_json.component.measures7.metric | wont_fix_issues
Creating variable : hotel_json.component.measures6.periods1.value | 0
Creating variable : hotel_json.component.measures6.periods1.index | 1
Creating variable : hotel_json.component.measures6.metric | new_security_remediation_effort
Creating variable : hotel_json.component.measures5.periods1.value | 0
Creating variable : hotel_json.component.measures5.periods1.index | 1
Creating variable : hotel_json.component.measures5.value | 333

If I want to send these variables into my next task WHICH is a JSON post METADATA, any idea how will I access these variables and their values??

**Comment by jeffpriz** [comment]
Glad it is showing for you now.  You can access the variables like any other variables in your pipeline. 
Ex:

$(hotel_json.component.measures5.value)

**Comment by kesavramesh** [comment]
Thx 

If there is no prefix then it will be 
$(component.measure5.value)???

**Comment by jeffpriz** [comment]
Right, you can turn off the prefix and you would end up with what you said.  Prefix comes in handy to avoid collisions when using multiple tasks, or when you might collide with other variables.

**Comment by jeffpriz** [comment]
@sedarby2018 anything to add to this issue?

**Comment by kesavramesh** [comment]
Unfortunately we are not able to get the info in the body of th JSON Here is the code snippet we are using
It is throwing 400 error code
Any suggestions?

{
                "ApplicationId": $(Hotels.Metrics.AppId),
                "AutomationProcessId": 45,
                "AutomationToolId": 22,
                "Description": "Static Code Analysis",
                "Version": "$(system.definitionId)",
                "Cycle": "$(system.definitionId)",
                "Passed": 1,
                "Failed": 0,
                "Blocked": 0,
                "StartDateTime": "2018/11/14 14:00:00",
                "EndDateTime": "2018/11/14 14:40:00",
                "MetaData": "[{"Project":"Hotels_PIP", "$(component.measures78.metric)":"$(component.measures78.value)" }]"
}

**Comment by jeffpriz** [comment]
I'm not sure I can help you debug your REST call, but you can verify your variable values using a Powershell task after the JSON file task to output values

**Comment by jeffpriz** [comment]
I just Published version 1.0.15 of the task to the marketplace, I adjusted the task Category to follow the newest Azure DevOps naming guidelines instead of the older VSTS category.  Not sure if that will help the issue with it taking a long time to show up in the task list or not, but at least this is now more correct for today's state

**Comment by sedarby2018** [comment]
No, for some reason it took like 8 hours for the extension to show up as a usable task.  I think we should be good now.
