### ISSUE TITLE
Question on use of the variables

### ISSUE THREAD

**Issue by Leif-Frederiksen** [jeffpriz/vsts-json-to-variable#14]
Hi,

I am wondering how I can reference the variables in a subsequent task. 
I put the variable name in as reference name in the Output Variables section of the Json to Variable task - see attached screen shot.
![image](https://user-images.githubusercontent.com/25172917/49362647-94d61c80-f6df-11e8-9686-f94d481078d7.png)

I get this message however when trying to save:
The pipeline is not valid. Job Phase_1: Step json.paths.zippedPackage has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.

I tried both putting in "json.paths.zippedPackage" and "$(json.paths.zippedPackage) and get the same result.

Please advise.

Regards
Leif

**Comment by GarethOates** [comment]
It looks as though you're trying to use a variable which would be created by the task, on the task itself.  My understanding of how this works would be that those variables are not available until the steps following this step.

**Comment by jeffpriz** [comment]
The Output variables is a section created by AzureDevOps by default, that is not something that is directly a part of my task. The Output variables is there to support multi-job pipelines. 

 My task creates variables based on the content of your JSON file.   You should put nothing in the output variables section.  It will create the variables for use by other tasks in the running build/release.  So if you have a Json that looks like
{
paths: {
zippedPackage:"something.zip" 
}
}

then you will get a variable json.paths.zippedPackage that you can utilize in other tasks in that build/release as $(json.paths.zippedPackage)
