### ISSUE TITLE
Incorrect handling of null value

### ISSUE THREAD

**Issue by MXClyde** [jeffpriz/vsts-json-to-variable#15]
Great task! I am receiving the following error when using this task on a json file that contains a null value:

` (node:3418) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of null`

PS. I have no experience with developing Azure DevOps tasks and TypeScript, but I will try to file a PR if I can in the coming days.

**Comment by jeffpriz** [comment]
Hey thanks for the issue, sorry i was out on Spring Break last week, so I didn't respond earlier.  I will take a peek at this in the next day or two.  Should be something i can get to well enough.  If you can, you can just PR over a change to the testJsonData.json file to include an example of the JSON you put in to generate the error, and that will help me test your exact case.

thanks
jeff

**Comment by MXClyde** [comment]
Thanks for your reply. No worries, found a workaround by adding a task that changes the JSON to replace the null with a value. I have created a PR: https://github.com/jeffpriz/vsts-json-to-variable/pull/16

**Comment by jeffpriz** [comment]
This has been troubling for me to re-produce.  The json file you provided runs fine with an empty string in my test process.  Also I've tried to reproduce this on my Azure DevOps instance with a value on one of my JSONs and have not seen this error occur.  

Could you run this in debug mode and provide me log output by any chance?

**Comment by MXClyde** [comment]
Unfortunately not, this was in a customer environment and I don't have access anymore (using Hosted Ubuntu agent). I propose to close this for now, as we managed to work around it as well. Thanks for the help!
