### ISSUE TITLE
Null values exception

### ISSUE THREAD

**Issue by kxag** [jeffpriz/vsts-json-to-variable#17]
If a value is null then the task stops creating variables 
....
....
Creating variable : PanasoftCommonUtilities.versions1.views1.type | implicit
(node:10812) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of null
##[section]Finishing: JSON to Variable

**Comment by jeffpriz** [comment]
Hey, I had somebody else report this issue not too long ago.  I was trying to reproduce it but was having trouble.. and they found a workaround and I haven't been able to figure this one out.  Could you tell me what Agent you're using? (Linux/Windows? What version? hosted? On-Prem?)  And could you run a build/release with the System.debug variable set to true and provide me the log from the task?

thanks

jeff

**Comment by kxag** [comment]
It is Windows I guess the latest version On premises.
I solved it by adding an if statement before the .tostring() calls on the compiled javascript file
So i guess you should do the same on the typescript file. It would be better to assign the null value to the variable (I just skipped the creation of the variable)

**Comment by jeffpriz** [comment]
still have been un-able to reproduce this issue. I've added some additional undefined checks around this logic that should help.. I just published 1.0.16 that should help here

**Comment by jeffpriz** [comment]
I'm going to close the issue for now.  If you still experience it, please let me know!
