### ISSUE TITLE
Make the prefix optional

### ISSUE THREAD

**Issue by CyborgWombat** [jeffpriz/vsts-json-to-variable#2]
Hey,

Could the prefix be optional?
I need to load a json with a f**ckton of configuration variables which are then substituted in config files (not just json files) for the app im deploying and I wouldn't want to have to rename all of them from PREFIX.{appvar} to {appvar}. I've tried simply leaving the prefix field empty but then it adds the default 'json' prefix.

Many thx,

**Comment by jeffpriz** [comment]
yeah, I can add a checkbox to give you the ability to generate the vars with no prefix.  That makes sense and shouldn't be too much effort.

thanks for the suggestion and feedback

**Comment by jeffpriz** [comment]
I just merged and published a new version of the task (now v 1.0.9) that handles this.  You now get a checkbox on the setup of the task to allow you to set it to have No prefix on the variable names.
