### ISSUE TITLE
Does it overwrite shared variables in the build pipeline?

### ISSUE THREAD

**Issue by aperisic** [jeffpriz/vsts-json-to-variable#20]

**Comment by jeffpriz** [comment]
if you have a variable "SomeName" and there is a JSON object "SomeName", yes, the variable "SomeName" will now have the value of the JSON object... 
So you can set a default value in the pipeline definition and set the value through the JSON.  If you want to avoid having this overwrite, you can set the Prefix option and the task and you would end up with two variable "SomeName" and "JSON.SomeName"
