### ISSUE TITLE
Do not show values in log (secrets)

### ISSUE THREAD

**Issue by woeterman94** [jeffpriz/vsts-json-to-variable#27]
Right now it outputs all variables in the log. Is there a way to turn this off?

**Comment by mhoult22** [comment]
I am using this extension now in a release pipeline, but concerns about security of having all the variables output to the log means I will have to stop using it.  It would be useful if this could be switched on/off as required.  Thank you.

**Comment by jeffpriz** [comment]
sorry for the delay on responding to this.  There is a new version of this task now published, you will no longer get the value of the variable created, only the variable name in the log.  You can turn on system.debug and the value will be logged there.

**Comment by mhoult22** [comment]
Thanks very much Jeff.  I’ll update the extension and try it out.

Michael
