### ISSUE TITLE
PowerShell access

### ISSUE THREAD

**Issue by CloudDevDan** [jeffpriz/vsts-json-to-variable#31]
I can access the set variable via inline PowerShell without issue (e.g. ```$(json.myVariable)``` but I cannot access them from within a PowerShell script (either via ```$(json.myVariable)``` or ```$env:json.myVariable)```.

Most likely I am doing something wrong, but I thought I'd run this by you either way to see what you think. Thanks.

**Comment by jeffpriz** [comment]
Hmm, so accessing a Pipeline variable within the Powershell script may not be directly possible, I can't say that I've actually ever really tried..  When I attempt to do such a thing I usually define a parameter in the powershell and then pass the parameter in using the value of the pipeline variable.. That way the powershell doesn't have to be tightly tied to the the pipeline, and the pipeline can cleanly pass values in to the powershell while leveraging the variables it is managing..

does that make sense?

**Comment by CloudDevDan** [comment]
Yes - that makes perfect sense. Honestly I'm kicking myself for not thinking of it before now as it's quite obvious now that you've mentioned in!

Thanks for getting back to me. Keep up the great work.
