### ISSUE TITLE
Json files with depth >3 not being expanded

### ISSUE THREAD

**Issue by KJaunay** [jeffpriz/vsts-json-to-variable#35]
If you have a json file with a depth >3 it won't be correctly expanded. The keys in the 4th level will be put into a single variable e.g. the below 

    "depth1":{
         "key1":"value1"
         "depth2":{
              "key2":"value2
              "depth3":{
                    "depth4key1":"value1",
                    "depth4key2":"value2",
                    "depth4key3":"value3"
               }
          }
     }

Will correctly create variables `depth1.key1`=`value1` and `depth1.depth2.key2`=`value2` but it will then create a variable with name `depth1.depth2.depth3`=`@{depth1.depth2.depth3.depth4key1=value1 ; depth1.depth2.depth3.depth4key2=value2 ; depth1.depth2.depth3.depth4key3=value3}`

**Comment by jeffpriz** [comment]
Hmm, I haven't experienced this as an issue, and it really shouldn't be.  Could you maybe double check your JSON to make sure it's formatted correctly? or provide?   I've set up a couple of tests just now to make sure I'm not missing anything, and I get it to work as expected.  
![image](https://user-images.githubusercontent.com/10476939/114198829-6143d680-9919-11eb-85f7-099940e138cb.png)
![image](https://user-images.githubusercontent.com/10476939/114198922-7882c400-9919-11eb-9b51-2fd8c6535bd3.png)


Or your example above (corrected JSON syntax)
![image](https://user-images.githubusercontent.com/10476939/114199030-8e908480-9919-11eb-8bdb-8ea9579e2e0f.png)
![image](https://user-images.githubusercontent.com/10476939/114199114-a1a35480-9919-11eb-9f10-73f8faddaf57.png)

**Comment by KJaunay** [comment]
@jeffpriz - You are absolutely correct, my mistake. I forgot I was manipulating the json and then creating a new json file 🤦‍♂️. In Powershell, if you don't specify a depth parameter when calling the ConvertTo-Json command, it will default to 3. If you then write that json object to a file, it formats as is. 

Thanks for the help! Managed to fix another issue I had as a result too.
