### ISSUE TITLE
how generate id and other info in 'task.json' file?

### ISSUE THREAD

**Issue by MujanMujan** [jeffpriz/vsts-json-to-variable#36]
Hi
may you explain to me how should achieve the 'id' that need in 'task.json' file? thanks.

**Comment by jeffpriz** [comment]
Hey Muhammad, so the Id is just a guid... so use your favorite guid generator.. other information about how to develop an extension for Azure DevOps can be found https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops
