### ISSUE TITLE
Accessing the created variable

### ISSUE THREAD

**Issue by biconix** [jeffpriz/vsts-json-to-variable#38]
this extension looks like it is exactly what i need.

But i am stuck in how to access the variable that is created?

I have a JSON file:
    {
      "IncludeAllSolutions": true
    }
in my Build Pipeline, I created and agent that uses the Json to Variables Step.
the variable is created:
Creating variable : json.IncludeAllSolutions

the second agent then has a condition:
eq(variables['json.IncludeAllSolutions'] , true)

but it expands to: eq(Null, True) Result:False

it seems not to find the new variable. I also tried creating a library variable (with the JSON prefix disabled) and also a local variable, but they never seem to be found.

What am I doing wrong?

**Comment by BigHoss** [comment]
@jeffpriz Could you specify that somewhere in the readme? was searching for 3 hours for this info. 

Thanks
