### ISSUE TITLE
Warnings about this task using Node 6 execution handler

### ISSUE THREAD

**Issue by rttremaine** [jeffpriz/vsts-json-to-variable#39]
Hi there. Firstly, thanks for the useful task!

We've noticed the following warnings appearing during builds:

`[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

Are you likely to update to the Node 10 handler? It would be good to know in advance if you decide not to so that we can start looking for alternatives, but hopefully you will be updating because this is such a useful build task!

Thanks in advance!

**Comment by fstani** [comment]
I've also came to ask about this. I'll see if this is an easy migration, if so I might create a PR for this

**Comment by jeffpriz** [comment]
thanks for pointing this one out.. I haven't seen this warning on my builds, curious what agent you're seeing that on.

I've updated the task and will be publishing the update in the next hour or so..
