### ISSUE TITLE
Node end of life

### ISSUE THREAD

**Issue by uk1988** [jeffpriz/vsts-json-to-variable#47]
Hej All

Recently we started getting following error:

`##[warning]Task 'JSON to Variable' version 1 (oneLuckiDevJson2Variable@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance`

Could the plugin be rebuilt and node version updated?

Best Regards,
Uros

**Comment by locduc-zenfolio** [comment]
confirmed. I get the same

**Comment by locduc-zenfolio** [comment]
Hi @jeffpriz, could you help to increase node version for this plugin? I appreciate your help

**Comment by jeffpriz** [comment]
I will get on this for sure! thanks for the heads up

**Comment by jeffpriz** [comment]
updated to support node 20, and tested and published.. Now in marketplace as v1.0.35

**Comment by uk1988** [comment]
Thank you very much!
