### ISSUE TITLE
Missing "dist" folder in new version (1.0.12)

### ISSUE THREAD

**Issue by ShannonKasperNoesis** [jeffpriz/vsts-json-to-variable#7]
I now get the following error when using the latest version of JSON to Variable (1.0.12). When browsing the file system on my build machine, it appears that the "dist" folder is missing. The "dist" folder, however, does exist for version 1.0.11. Let me know if there are any workarounds I can do. Thanks
```
File not found: '/home/noesis/azure-devops-agent/_work/_tasks/oneLuckiDevJson2Variable_6f9cdff3-a6b9-47e1-90a8-6590ba11e157/1.0.12/./dist/json2variable.js'
```

**Comment by rcampbell22** [comment]
Same issue here - running on a 'hosted macOS' agent if it helps diagnose the issue.

**Comment by jeffpriz** [comment]
whoa, sorry!  I just uploaded v 1.0.13 that should fix this.  Sorry for the troubles.
