### ISSUE TITLE
SyntaxError: Unexpected token } in JSON

### ISSUE THREAD

**Issue by R0binT** [jeffpriz/vsts-json-to-variable#9]
Hi,
I got an issue when using your task for a release pipeline on Azure Devops.

I try to parse a swagger.json file that I made. I know the json is correct because I use it everywhere else.

But on your task, I get that error :

<img width="1149" alt="screenshot 2018-10-31 at 15 41 59" src="https://user-images.githubusercontent.com/6819007/47795851-87fe8b80-dd23-11e8-9b43-378688831f6f.png">

I know it looks like a wrongly formated json, But I assure you, it is completly correct.

Thanks for your help :)

**Comment by jeffpriz** [comment]
Hey Robin,
can you set your build/release to system.debug = true and pass me the output of the task? and could you also provide the json file that is causing the error?  I have seen this error pop up in our production tfs systems but only when there was indeed a JSON error. 

This task doesn't do anything particularly tricky to get the object from the JSON, it simply reads the file and then does a JSON.parse on it. 

thanks

Jeff

**Comment by R0binT** [comment]
Ok so I have no idea why, but I don't have the problem anymore.

Sorry to have bothered you.

thanks again. Have a nice day

**Comment by 6heads** [comment]
Similar problem here.

![grafik](https://user-images.githubusercontent.com/46749895/63502894-bde94800-c4ce-11e9-815d-2c22dc0bfa08.png)

At first I thought maybe it's the crlf and compressed the json, but it's still there.

This is the powershell script that generates the json-file:

![grafik](https://user-images.githubusercontent.com/46749895/63503085-1f111b80-c4cf-11e9-8dc3-184c668b5534.png)

This is the build step JSON to variable:

![grafik](https://user-images.githubusercontent.com/46749895/63503720-4d432b00-c4d0-11e9-9ce3-23d8625cf787.png)

This is the generated file (I renamed it to be able to upload but shouldn't matter):

[return.txt](https://github.com/jeffpriz/vsts-json-to-variable/files/3529398/return.txt)

**Comment by anderswendt** [comment]
> Similar problem here.
> 
> ![grafik](https://user-images.githubusercontent.com/46749895/63502894-bde94800-c4ce-11e9-815d-2c22dc0bfa08.png)

I had the same issue. Turns out my json file was UTF-8 BOM encoded. I saved it as UTF-8 and then the task succeeded.

**Comment by 6heads** [comment]
> 
> 
> > Similar problem here.
> > ![grafik](https://user-images.githubusercontent.com/46749895/63502894-bde94800-c4ce-11e9-815d-2c22dc0bfa08.png)
> 
> I had the same issue. Turns out my json file was UTF-8 BOM encoded. I saved it as UTF-8 and then the task succeeded.

Thanks for pointing out to the right direction.

[Default](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1#parameters) in Powershell 5.1 is Unicode. 
I tried UTF8, BigEndianUnicode, UTF7, UTF32. Those all didn't work out.

ASCII, Default and OEM seem to work.
> ASCII Uses ASCII (7-bit) character set.
> Default Uses the encoding that corresponds to the system's active code page (usually ANSI).
> OEM Uses the encoding that corresponds to the system's current OEM code page.

I'll stick with ASCII for now, because it seems to be the only system independent.

**Comment by jeffpriz** [comment]
thanks @anderswendt for answering this one so quickly.. Yeah I was going to respond that file encoding is going to be the culprit.. it expects UTF8 (and I know earlier versions did choke on UTF-8- BOM but current version should handle the BOM today).

I have had it on my mental backlog to look into supporting other file encoding formats, but there have been no issues on that so far.. I may re-evaluate adding that support for other file encoding formats
